workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 60
    instance_type: linux
    environment:
      flutter: stable
      groups:
        - android-signing
    scripts:
      - flutter pub get
      - flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios-workflow:
    name: iOS Release Build
    max_build_duration: 90
    instance_type: mac_mini
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios-signing
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
