workflows:
  android:
    name: Android Build  
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa   
