workflows:
  ios:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - flutter pub get
      - cd ios && pod install && cd ..
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa   
